======= INICIANDO FLUXO DE AUTORIZAÇÃO SHOPEE =======
Usuário autenticado: {
  claims: {
    aud: '73ee031f-24e8-4b77-96e8-2cd2724cf5f2',
    exp: 1748304691,
    iat: 1748301091,
    iss: 'https://replit.com/oidc',
    sub: '41750934',
    email: 'llouback4@gmail.com',
    at_hash: 'B7u10kg2zbokUbigp1iPwQ',
    username: 'llouback4',
    auth_time: 1748301091,
    last_name: 'Louback',
    first_name: 'Lucas'
  },
  expires_at: 1748304691,
  access_token: 'qO0NH3wGwOUTEJshtDaWbrRYEQOPbIfZzLyYGUWowFl',
  refresh_token: 'ZOV3B0zWUkGnL3yeMklS2dz-8mZryBv4IQsBpxZlzQd'
}
Ambiente: development
Informações de configuração da API:
Partner ID: 2011285
URL de redirecionamento configurada: undefined
===================================================
URL de redirecionamento que será usada: https://cipshopee.replit.app/api/shopee/callback
Error starting Shopee OAuth flow: Error [TransformError]: Transform failed with 1 error:
/home/runner/workspace/server/shopee/auth.ts:1:2: ERROR: Expected ";" but found "will"
    at failureErrorWithLog (/home/runner/workspace/node_modules/tsx/node_modules/esbuild/lib/main.js:1476:15)
    at /home/runner/workspace/node_modules/tsx/node_modules/esbuild/lib/main.js:755:50
    at responseCallbacks.<computed> (/home/runner/workspace/node_modules/tsx/node_modules/esbuild/lib/main.js:622:9)
    at handleIncomingPacket (/home/runner/workspace/node_modules/tsx/node_modules/esbuild/lib/main.js:677:12)
    at Socket.readFromStdout (/home/runner/workspace/node_modules/tsx/node_modules/esbuild/lib/main.js:600:7)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
    at Pipe.onStreamRead (node:internal/stream_base_commons:191:23)
Verificando conexão com banco de dados...
Conexão com banco de dados estabelecida com sucesso
12:42:09 AM [express] GET /api/shopee/authorize 500 in 144ms :: {"message":"Failed to start authoriza…
Verificando conexão com banco de dados...
Conexão com banco de dados estabelecida com sucesso
Verificando conexão com banco de dados...
Conexão com banco de dados estabelecida com sucesso
